version: "3"
services:

  # redis:
  #   image: redis:alpine
  #   volumes:
  #     - ./redis-data:/data
  #   ports:
  #     - "6379:6379"
  # db:
  #   image: postgres:9.6.5
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   ports:
  #     - "15432:5432"
  app:
    build: .
    command: python pychain/app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - miner
  miner:
    build: .
    command: python pychain/miner.py
    volumes:
      - .:/code
    ports:
      - "5001:5001"

